// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package service

import (
	"io"
	http "net/http"
	time "time"

	github_com_foomo_contentserver_content "github.com/foomo/contentserver/content"
	gotsrpc "github.com/foomo/gotsrpc/v2"
	github_com_foomo_redirects_v2_domain_redirectdefinition "github.com/foomo/redirects/v2/domain/redirectdefinition"
	github_com_foomo_redirects_v2_domain_redirectdefinition_store "github.com/foomo/redirects/v2/domain/redirectdefinition/store"
)

const (
	AdminServiceGoTSRPCProxyCreate       = "Create"
	AdminServiceGoTSRPCProxyDelete       = "Delete"
	AdminServiceGoTSRPCProxySearch       = "Search"
	AdminServiceGoTSRPCProxyUpdate       = "Update"
	AdminServiceGoTSRPCProxyUpdateStates = "UpdateStates"
)

type AdminServiceGoTSRPCProxy struct {
	EndPoint string
	service  AdminService
}

func NewDefaultAdminServiceGoTSRPCProxy(service AdminService) *AdminServiceGoTSRPCProxy {
	return NewAdminServiceGoTSRPCProxy(service, "/services/redirectdefinition/admin")
}

func NewAdminServiceGoTSRPCProxy(service AdminService, endpoint string) *AdminServiceGoTSRPCProxy {
	return &AdminServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
	}
}

// ServeHTTP exposes your service
func (p *AdminServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}
	defer io.Copy(io.Discard, r.Body) // Drain Request Body

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	callStats, callStatsOk := gotsrpc.GetStatsForRequest(r)
	if callStatsOk {
		callStats.Func = funcName
		callStats.Package = "github.com/foomo/redirects/v2/domain/redirectdefinition/service"
		callStats.Service = "AdminService"
	}
	switch funcName {
	case AdminServiceGoTSRPCProxyCreate:
		var (
			args []any
			rets []any
		)
		var (
			arg_def    *github_com_foomo_redirects_v2_domain_redirectdefinition_store.RedirectDefinition
			arg_locale string
		)
		args = []any{&arg_def, &arg_locale}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStatsOk {
			executionStart = time.Now()
		}
		rw := gotsrpc.ResponseWriter{ResponseWriter: w}
		createRet, createRet_1 := p.service.Create(&rw, r, arg_def, arg_locale)
		if callStatsOk {
			callStats.Execution = time.Since(executionStart)
		}
		if rw.Status() == http.StatusOK {
			rets = []any{createRet, createRet_1}
			if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
				gotsrpc.ErrorCouldNotReply(w)
				return
			}
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case AdminServiceGoTSRPCProxyDelete:
		var (
			args []any
			rets []any
		)
		var (
			arg_id string
		)
		args = []any{&arg_id}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStatsOk {
			executionStart = time.Now()
		}
		rw := gotsrpc.ResponseWriter{ResponseWriter: w}
		deleteRet := p.service.Delete(&rw, r, arg_id)
		if callStatsOk {
			callStats.Execution = time.Since(executionStart)
		}
		if rw.Status() == http.StatusOK {
			rets = []any{deleteRet}
			if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
				gotsrpc.ErrorCouldNotReply(w)
				return
			}
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case AdminServiceGoTSRPCProxySearch:
		var (
			args []any
			rets []any
		)
		var (
			arg_params *github_com_foomo_redirects_v2_domain_redirectdefinition.SearchParams
		)
		args = []any{&arg_params}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStatsOk {
			executionStart = time.Now()
		}
		rw := gotsrpc.ResponseWriter{ResponseWriter: w}
		searchRet, searchRet_1 := p.service.Search(&rw, r, arg_params)
		if callStatsOk {
			callStats.Execution = time.Since(executionStart)
		}
		if rw.Status() == http.StatusOK {
			rets = []any{searchRet, searchRet_1}
			if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
				gotsrpc.ErrorCouldNotReply(w)
				return
			}
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case AdminServiceGoTSRPCProxyUpdate:
		var (
			args []any
			rets []any
		)
		var (
			arg_def *github_com_foomo_redirects_v2_domain_redirectdefinition_store.RedirectDefinition
		)
		args = []any{&arg_def}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStatsOk {
			executionStart = time.Now()
		}
		rw := gotsrpc.ResponseWriter{ResponseWriter: w}
		updateRet := p.service.Update(&rw, r, arg_def)
		if callStatsOk {
			callStats.Execution = time.Since(executionStart)
		}
		if rw.Status() == http.StatusOK {
			rets = []any{updateRet}
			if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
				gotsrpc.ErrorCouldNotReply(w)
				return
			}
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case AdminServiceGoTSRPCProxyUpdateStates:
		var (
			args []any
			rets []any
		)
		var (
			arg_ids   []*github_com_foomo_redirects_v2_domain_redirectdefinition_store.EntityID
			arg_state bool
		)
		args = []any{&arg_ids, &arg_state}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStatsOk {
			executionStart = time.Now()
		}
		rw := gotsrpc.ResponseWriter{ResponseWriter: w}
		updateStatesRet := p.service.UpdateStates(&rw, r, arg_ids, arg_state)
		if callStatsOk {
			callStats.Execution = time.Since(executionStart)
		}
		if rw.Status() == http.StatusOK {
			rets = []any{updateStatesRet}
			if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
				gotsrpc.ErrorCouldNotReply(w)
				return
			}
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	default:
		gotsrpc.ClearStats(r)
		gotsrpc.ErrorFuncNotFound(w)
	}
}

const (
	InternalServiceGoTSRPCProxyCreateRedirectsFromContentserverexport = "CreateRedirectsFromContentserverexport"
	InternalServiceGoTSRPCProxyGetRedirects                           = "GetRedirects"
)

type InternalServiceGoTSRPCProxy struct {
	EndPoint string
	service  InternalService
}

func NewDefaultInternalServiceGoTSRPCProxy(service InternalService) *InternalServiceGoTSRPCProxy {
	return NewInternalServiceGoTSRPCProxy(service, "/services/redirectdefinition/internal")
}

func NewInternalServiceGoTSRPCProxy(service InternalService, endpoint string) *InternalServiceGoTSRPCProxy {
	return &InternalServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
	}
}

// ServeHTTP exposes your service
func (p *InternalServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}
	defer io.Copy(io.Discard, r.Body) // Drain Request Body

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	callStats, callStatsOk := gotsrpc.GetStatsForRequest(r)
	if callStatsOk {
		callStats.Func = funcName
		callStats.Package = "github.com/foomo/redirects/v2/domain/redirectdefinition/service"
		callStats.Service = "InternalService"
	}
	switch funcName {
	case InternalServiceGoTSRPCProxyCreateRedirectsFromContentserverexport:
		var (
			args []any
			rets []any
		)
		var (
			arg_oldState map[string]*github_com_foomo_contentserver_content.RepoNode
			arg_newState map[string]*github_com_foomo_contentserver_content.RepoNode
		)
		args = []any{&arg_oldState, &arg_newState}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStatsOk {
			executionStart = time.Now()
		}
		rw := gotsrpc.ResponseWriter{ResponseWriter: w}
		createRedirectsFromContentserverexportRet := p.service.CreateRedirectsFromContentserverexport(&rw, r, arg_oldState, arg_newState)
		if callStatsOk {
			callStats.Execution = time.Since(executionStart)
		}
		if rw.Status() == http.StatusOK {
			rets = []any{gotsrpc.ErrorReply(createRedirectsFromContentserverexportRet)}
			if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
				gotsrpc.ErrorCouldNotReply(w)
				return
			}
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case InternalServiceGoTSRPCProxyGetRedirects:
		var (
			args []any
			rets []any
		)
		var executionStart time.Time
		if callStatsOk {
			executionStart = time.Now()
		}
		rw := gotsrpc.ResponseWriter{ResponseWriter: w}
		getRedirectsRet, getRedirectsRet_1 := p.service.GetRedirects(&rw, r)
		if callStatsOk {
			callStats.Execution = time.Since(executionStart)
		}
		if rw.Status() == http.StatusOK {
			rets = []any{getRedirectsRet, gotsrpc.ErrorReply(getRedirectsRet_1)}
			if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
				gotsrpc.ErrorCouldNotReply(w)
				return
			}
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	default:
		gotsrpc.ClearStats(r)
		gotsrpc.ErrorFuncNotFound(w)
	}
}
